version: '3.8'

services:
  django:
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/django/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
      - engine

  db:
    image: postgres:12.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lovelace
      - POSTGRES_PASSWORD=lovelace
      - POSTGRES_DB=lovelace_dev

  engine:
    image: projectlovelace/lovelace-engine
    command: gunicorn --worker-tmp-dir /dev/shm --workers 1 --log-level debug --timeout 600 --preload --reload --bind 0.0.0.0:14714 engine.api:app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 14714

volumes:
  postgres_data:
