version: '3.7'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/django/static_prod
      - media_volume:/home/app/django/media
    ports:
      - 1337:80
    depends_on:
      - django

  django:
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    command: gunicorn lovelace.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/django/static_prod
      - media_volume:/home/app/django/media
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - engine

  db:
    image: postgres:12.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  engine:
    image: projectlovelace/lovelace-engine
    command: gunicorn --worker-tmp-dir /dev/shm --workers 1 --log-level debug --timeout 600 --preload --reload --bind 0.0.0.0:14714 engine.api:app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 14714

volumes:
  postgres_data:
  static_volume:
  media_volume:
